baseURL = 'https://fysh-fyve.github.io/'
languageCode = 'en-us'
title = 'Fysh'
markup.goldmark.renderer.unsafe = true

minify.minifyOutput = true

[[menus.main]]
name = 'Docs'
pageRef = '/docs'
weight = 20

[[menus.main]]
name = 'Source'
url = 'https://github.com/Fysh-Fyve/fysh'
weight = 20

# [[menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 30

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"


[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static"
target = "static"


[[module.mounts]]
source = "../web-interpreter/out/opt"
target = "static"
