name: Create fyshls release

on:
  push:
    tags:
      - 'v*.*.*'  # Matches version tags like v1.0.0

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.23']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Build
      run: |
        go run ./pkg/fyshls/cmd/install fyshls ./pkg/fyshls

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}
        asset_path: fyshls
        asset_name: fyshls-${{ matrix.os }}
        asset_content_type: application/octet-stream
